# Generated by Django 3.2 on 2021-05-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210502_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categori',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategori',
            new_name='subcategory',
        ),
    ]
